version: '2'
services:
  postgres:
    restart: always
    image: postgres:17.5-alpine
    ports:
      - "5433:5432"
    volumes:
      - ".pgdata:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super-password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=trading-analysis